name: LoveBuild
on:
  push:
    branches: [ master ]
jobs:
  build-bug:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: nhartland/love-build@master
      id: love-build
      with:
        app_name: 'Bug'
        love_version: '11.3'
        source_dir: '/'
    - uses: actions/upload-artifact@v1
      with:
        name: hw_macos-build
        path: ${{ steps.love-build.outputs.macos-filename }}
    - uses: actions/upload-artifact@v1
      with:
        name: hw_win32-build
        path: ${{ steps.love-build.outputs.win32-filename }}
    - uses: actions/upload-artifact@v1
      with:
        name: hw_win64-build
        path: ${{ steps.love-build.outputs.win64-filename }}
    - uses: actions/upload-artifact@v1
      with:
        name: hw_love-build
        path: ${{ steps.love-build.outputs.love-filename }}
