name: LoveBuild
on:
  push:
    branches: [ main ]
jobs:
  build-bug:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: nhartland/love-build@v1-beta2
      with:
        app_name: 'Bug'
        love_version: '11.3'
    - uses: actions/upload-artifact@v1
      with:
        name: built-applications
        path: 'release'
